name: Gemini Review Reminder

on:
  push:
    branches: [main]

jobs:
  remind-pr-creation:
    runs-on: ubuntu-latest
    # Only run if it's not from a PR merge
    if: github.event.head_commit.message && !contains(github.event.head_commit.message, 'Merge pull request')
    
    steps:
      - name: Create reminder issue
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = context.sha.substring(0, 7);
            const commitMessage = context.payload.head_commit.message.split('\n')[0];
            const commitUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}`;
            
            // Check if reminder issue already exists for this commit
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'gemini-review-needed',
              state: 'open'
            });
            
            const existingIssue = issues.find(issue => 
              issue.body && issue.body.includes(context.sha)
            );
            
            if (!existingIssue) {
              const { data: issue } = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🤖 Gemini Review Needed: ${commitMessage}`,
                body: `A direct push to main was detected. To get Gemini Code Assist to review this code:

1. Create a new branch from this commit
2. Create a pull request to main
3. Gemini will automatically review the PR

**Commit Details:**
- SHA: ${context.sha}
- Message: ${commitMessage}
- Author: @${context.actor}
- [View Commit](${commitUrl})

**Quick Commands:**
\`\`\`bash
# Create a branch from this commit
git checkout -b review/${commitSha} ${context.sha}
git push origin review/${commitSha}

# Then create a PR via GitHub UI or CLI:
gh pr create --base main --head review/${commitSha} --title "${commitMessage}" --body "Review of direct commit ${context.sha}"
\`\`\`

---
*This issue was automatically created because Gemini Code Assist only reviews pull requests, not direct pushes.*`,
                labels: ['gemini-review-needed', 'automated']
              });
              
              console.log(`Reminder issue created: ${issue.html_url}`);
            } else {
              console.log('Reminder issue already exists for this commit');
            }